//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quests.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int IdOrder { get; set; }
        public int IdQuestStuff { get; set; }
        public int IdClient { get; set; }
        public System.DateTime GameDateTime { get; set; }
        public int NuberPlayers { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Quest Quest { get; set; }
    }
}
