//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quests.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MainInfOrd
    {
        public string Номер_телефона_клиента { get; set; }
        public string Название_квеста { get; set; }
        public System.DateTime Дата_проведения_квеста { get; set; }
        public int Кол_во_игроков { get; set; }
        public decimal Цена_за_квест { get; set; }
        public int Макс__число_игроков { get; set; }
        public decimal Цена_за_каждого_лишнего_игрока { get; set; }
        public int Персональная_скидка { get; set; }
        public Nullable<decimal> Сумма { get; set; }
    }
}
